### PR TITLE
Add parallelization

### PR DESCRIPTION
**Pull request by jonashaag**
- Parallel download
- Parallel mixture creation

What's still slow is the metadata writing part (`add_to_metrics_metadata` or the `for md_df in md_dic` loop), haven't investigated further here.

I tested this once and it seems to work well.

Haven't given much time to properly formatting the code :-)

### CODE REVIEW

**Review by mpariente — APPROVED** [review]
Looks good thank you ! 
I'll let Joris review as well and merge if it's ok for him.

**Comment by JorisCos** [comment]
Hello, Thanks for the PR. 
It looks good to me too.
I will run a quick test to double check and then I will merge.
Thanks again ! 🚀

**Comment by JorisCos** [comment]
error 

I tried to run the recipe directly from your fork but it broke during the augmentation process.
I haven't look much into it yet but if you have any idea I take it :)

**Comment by jonashaag** [comment]
You should update `tqdm` :-)

**Comment by emanueleielo** [comment]
> You should update `tqdm` :-)

HI! How much the mix will require with this edit? Because I'm running it on colab and looks like infinite, after 24hours still working and is at 500GB of files

**Pull request merged**
